obj-$(CONFIG_RESET_CONTROLLER) += core.o
obj-$(CONFIG_RESET_CONTROLLER_OXNAS) += reset-ox820.o
obj-$(CONFIG_ARCH_SOCFPGA) += reset-socfpga.o
obj-$(CONFIG_ARCH_BERLIN) += reset-berlin.o
obj-$(CONFIG_ARCH_SUNXI) += reset-sunxi.o
obj-$(CONFIG_ARCH_STI) += sti/
